version: '1'
services:

    go-api:
        container_name: dockerfile
        build:
          dockerfile: Dockerfile
        environment: 
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRTUAL_PORT=${VIRTUAL_PORT}
            - SELF_SIGNED_HOST=${SELF_SIGNED_HOST}

            - AUTH0_DOMAIN=${AUTH0_DOMAIN}
            - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
            - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
            - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
            - AUTH0_LOGOUT_URL=${AUTH0_LOGOUT_URL}

            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_PASSWORD=${DB_PASSWORD}

            - JWT_SECRET=${JWT_SECRET}
        networks:
            - nginx-proxy-network
        volumes:
            - ./src:/app

networks:
    nginx-proxy-network:
        external: true